import js from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import prettierConfig from 'eslint-config-prettier';
import security from 'eslint-plugin-security';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      '.astro/**',
      '*.cjs',
      'scratch*.js',
      'test_*.js',
      'fix_*.cjs',
      'public/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        queueMicrotask: 'readonly',
        fetch: 'readonly',
        navigator: 'readonly',
        alert: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        React: 'readonly',
        HTMLModElement: 'readonly',
        HTMLInputElement: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        AbortController: 'readonly',
        MessageChannel: 'readonly',
        Node: 'readonly',
        OffscreenCanvas: 'readonly',
        matchMedia: 'readonly',
        navigation: 'readonly',
        reportError: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescriptEslint,
      security: security,
    },
    rules: {
      ...typescriptEslint.configs.recommended.rules,
      ...prettierConfig.rules,
      ...security.configs.recommended.rules,
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-undef': 'off',
      'no-unused-vars': 'warn',
      'no-empty': 'warn',
      'no-prototype-builtins': 'warn',
      'no-fallthrough': 'warn',
      'no-cond-assign': 'warn',
      'no-useless-assignment': 'warn',
      'no-useless-escape': 'warn',
      'no-control-regex': 'warn',
      'no-constant-condition': 'warn',
      'getter-return': 'warn',
      'valid-typeof': 'warn',
      'no-unreachable': 'warn',
      'no-misleading-character-class': 'warn',
    },
  },
  {
    files: ['**/*.{js,jsx}'],
    ignores: [
      'node_modules/**',
      'dist/**',
      '.astro/**',
      '*.cjs',
      'scratch*.js',
      'test_*.js',
      'fix_*.cjs',
      'public/**',
    ],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        queueMicrotask: 'readonly',
        fetch: 'readonly',
        navigator: 'readonly',
        alert: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        React: 'readonly',
        HTMLModElement: 'readonly',
        HTMLInputElement: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        AbortController: 'readonly',
        MessageChannel: 'readonly',
        Node: 'readonly',
        OffscreenCanvas: 'readonly',
        matchMedia: 'readonly',
        navigation: 'readonly',
        reportError: 'readonly',
        __REACT_DEVTOOLS_GLOBAL_HOOK__: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'warn',
      'no-prototype-builtins': 'warn',
      'no-fallthrough': 'warn',
      'no-cond-assign': 'warn',
      'no-useless-assignment': 'warn',
      'no-useless-escape': 'warn',
      'no-control-regex': 'warn',
      'no-constant-condition': 'warn',
      'getter-return': 'warn',
      'valid-typeof': 'warn',
      'no-unreachable': 'warn',
      'no-misleading-character-class': 'warn',
    },
  },
];
